### ISSUE TITLE
Getting started should note warning/error can be ignored

### ISSUE THREAD

**Issue by orineman** [open-amt-cloud-toolkit/docs#222]
V 2.3.1 installed on macOS 12.2

[Set Up Page](https://open-amt-cloud-toolkit.github.io/docs/2.3/GetStarted/setup/)

The "docker-compose pull" step may produce the following warning/error:

```
WARNING: Some service image(s) must be built from source by running:
    docker compose build db webui rps mps mpsrouter
Error response from daemon: pull access denied for sslpostgres, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

It is tremendously confusing for those unfamiliar with Docker so the documentation should note that it can safely be ignored.

**Comment by rsdmike** [comment]
We have fixed this in the v2.5 release. Thanks!
