### ISSUE TITLE
UI toolkit tutorial has bad string for ui-toolkit-react version

### ISSUE THREAD

**Issue by orinem** [open-amt-cloud-toolkit/docs#232]
The following is being displayed in the tutorial:

```
npm install @open-amt-cloud-toolkit/ui-toolkit-react@{{ no such element: dict object['ui_react'] }}
```

It seems that the automation of the current version number has failed.  At the moment, I assume it should display:

```
npm install @open-amt-cloud-toolkit/ui-toolkit-react@2.0.4
```

**Comment by bwendlandt-intel** [comment]
Hi @orinem, thanks for calling this out! You are correct in your assumption.  It is now fixed. Closing this issue.
