### ISSUE TITLE
More plugin requirements for Local Development

### ISSUE THREAD

**Issue by orinem** [open-amt-cloud-toolkit/docs#234]
I had to install mkdocs-macros-plugin and mkdocs-img2fig-plugin in order to run locally on macOS Monterey 12.2.

python version 3.8.9 and pip version 22.2.1

**Comment by bwendlandt-intel** [comment]
Thanks for the shout out, looks like we had the Dockerfile updated but not the local readme path updated with the latest plugins used.  Resolved in PR #235 

Closing Issue.
