### ISSUE TITLE
Update EKS documentation with additional steps for deploying EBS CSI driver add-on

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/docs#253]
Customers have reported that additional EBS CSI driver add-on is required to create persistent volume for Vault.  The attached document describes the steps needed to be included in EKS deployment instructions.

[EKS extra steps.docx](https://github.com/open-amt-cloud-toolkit/docs/files/10106300/EKS.extra.steps.docx)

**Comment by bwendlandt-intel** [comment]
Closing, new EKS changes (IAM, EBS CSI driver) addressed in #259 and now merged into live docs site. Thanks!
