### ISSUE TITLE
Needs to update sample webui documentation for local deployment

### ISSUE THREAD

**Issue by vyshali-chitikeshi** [open-amt-cloud-toolkit/docs#32]
With local deployment, we need to update app_config.js file under sample-webui/src with mps and rps server  ip addresses and port numbers, don't see those steps in documentaiton.

**Comment by bwendlandt-intel** [comment]
Hi Vyshali,
Updating app.config.js as well as .mpsrc/.rpsrc are currently handled by a Makefile/Powershell script. However, the makefile currently has a bug causing it to not update cors_origin. I will leave this issue open until I can resolve that in the [open-amt-cloud-toolkit repo](https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit).

Also, additional documentation has been added for navigating to the MPS webserver before the SampleUI.

Thanks,
Bryan
