### ISSUE TITLE
Docs should indicated when connecting with KVM won't work in CCM Mode

### ISSUE THREAD

**Issue by rsdmike** [open-amt-cloud-toolkit/docs#53]

**Comment by matt-primrose** [comment]
@bwendlandt-intel has this issue been resolved?

**Comment by bwendlandt-intel** [comment]
This is mentioned during the [CCM vs ACM branch](https://open-amt-cloud-toolkit.github.io/docs/1.4/General/createCIRAConfig/) as well as in a [note when showcasing the device dashboard](https://open-amt-cloud-toolkit.github.io/docs/1.4/General/manageDevice/).  These have been included for a few versions.  Open to opinions if it is enough or is too easily skippable.

**Comment by matt-primrose** [comment]
@rsdmike Docs update seems to cover this now.  Mike, you good with closing this?
